server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_SERVER}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update